package ca.mcgill.ecse.climbsafe.javafx.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.control.Tab;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class BundlesPageController {
	@FXML
	private TabPane bundlesPageTabPane;
	@FXML
	private Tab addTab;
	@FXML
	private TextField addName;
	@FXML
	private TextField addDiscount;
	@FXML
	private TableView addEquipTable;
	@FXML
	private TableColumn addEquipTableName;
	@FXML
	private TableColumn addEquipTableWeight;
	@FXML
	private TableColumn addEquipTablePrice;
	@FXML
	private TableColumn addEquipTableQuantity;
	@FXML
	private Button addClear;
	@FXML
	private Button addADD;
	@FXML
	private TextField addTotalCost;
	@FXML
	private Tab updateTab;
	@FXML
	private TextField updateName;
	@FXML
	private TextField updateDiscount;
	@FXML
	private TableView addEquipTable1;
	@FXML
	private TableColumn updateEquipTableName;
	@FXML
	private TableColumn updateEquipTableWeight;
	@FXML
	private TableColumn updateEquipTablePrice;
	@FXML
	private TableColumn updateEquipTableQuantity;
	@FXML
	private Button updateClear;
	@FXML
	private Button updateAutofill;
	@FXML
	private Button updateUpdate;
	@FXML
	private TextField updateTotalCost;
	@FXML
	private Tab delTab;
	@FXML
	private TableView delTable;
	@FXML
	private TableColumn delTableName;
	@FXML
	private TableColumn delTableDiscount;
	@FXML
	private TableColumn delTableEquipments;
	@FXML
	private TableColumn delTableQuantities;
	@FXML
	private Button delClearSelection;
	@FXML
	private Button delDelete;
	@FXML
	private Button delModifySelected;

	// Event Listener on TextField[#addName].onAction
	@FXML
	public void addDoAdd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addClear].onAction
	@FXML
	public void addDoClear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addADD].onAction
	@FXML
	public void addDoADD(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#updateName].onAction
	@FXML
	public void updateDoUpdate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateClear].onAction
	@FXML
	public void updateDoClear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateAutofill].onAction
	@FXML
	public void updateDoAutofill(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delClearSelection].onAction
	@FXML
	public void delDoClearSelection(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delDelete].onAction
	@FXML
	public void delDoDelete(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delModifySelected].onAction
	@FXML
	public void delDoModifySelected(ActionEvent event) {
		// TODO Autogenerated
	}
}
