package ca.mcgill.ecse.climbsafe.javafx.controllers;

import javafx.fxml.FXML;

import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet4Controller;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class EquipmentsPageController {
	@FXML
	private TextField addName;
	@FXML
	private TextField addWeight;
	@FXML
	private TextField addPrice;
	@FXML
	private Button addClear;
	@FXML
	private Button addAdd;
	@FXML
	private TextField addTotalCost;
	@FXML
	private TextField updateName;
	@FXML
	private TextField updateWeight;
	@FXML
	private TextField updatePrice;
	@FXML
	private Button updateClear;
	@FXML
	private Button updateAutofill;
	@FXML
	private Button updateUpdate;
	@FXML
	private TextField updateTotalCost;
	@FXML
	private TableView delTable;
	@FXML
	private TableColumn delTableName;
	@FXML
	private TableColumn delTableWeight;
	@FXML
	private TableColumn delTablePrice;
	@FXML
	private TableColumn delTableQuantity;
	@FXML
	private Button delClearSelection;
	@FXML
	private Button delDelete;
	@FXML
	private Button delModifySelected;

	// Event Listener on TextField[#addName].onAction
	@FXML
	public void addDoAdd(ActionEvent event) {

	}
	// Event Listener on TextField[#addWeight].onAction
	@FXML
	public void addDoAdd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#addPrice].onAction
	@FXML
	public void addDoAdd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addClear].onAction
	@FXML
	public void addDoclear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addAdd].onAction
	@FXML
	public void addDoAdd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#updateName].onAction
	@FXML
	public void updateDoUpdate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#updateWeight].onAction
	@FXML
	public void updateDoUpdate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#updatePrice].onAction
	@FXML
	public void updateDoUpdate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateClear].onAction
	@FXML
	public void updateDoClear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateAutofill].onAction
	@FXML
	public void updateDoAutofill(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateUpdate].onAction
	@FXML
	public void updateDoUpdate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delClearSelection].onAction
	@FXML
	public void delDoClearSelection(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delDelete].onAction
	@FXML
	public void delDoDelete(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delModifySelected].onAction
	@FXML
	public void delDoModifySelected(ActionEvent event) {
		// TODO Autogenerated
	}
}
