package ca.mcgill.ecse.climbsafe.javafx.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.control.Tab;

import javafx.scene.control.PasswordField;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class GuidesPageController {
	@FXML
	private TabPane membersPageTabPane;
	@FXML
	private Tab regTab;
	@FXML
	private TextField regGuideEmail;
	@FXML
	private PasswordField regGuidePassword;
	@FXML
	private TextField regPasswordShow;
	@FXML
	private TextField regGuideName;
	@FXML
	private TextField regGuideContact;
	@FXML
	private Button regGuideClear;
	@FXML
	private Button regGuideRegister;
	@FXML
	private Tab modTab;
	@FXML
	private TextField modGuideEmail;
	@FXML
	private PasswordField modGuidePassword;
	@FXML
	private TextField modPasswordShow;
	@FXML
	private TextField modGuideName;
	@FXML
	private TextField modGuideContact;
	@FXML
	private Button modGuideClear;
	@FXML
	private Button modGuideAutofill;
	@FXML
	private Button modGuideModify;
	@FXML
	private Tab delTab;
	@FXML
	private TableView delTable;
	@FXML
	private TableColumn delGuideTableName;
	@FXML
	private TableColumn delGuideTableEmail;
	@FXML
	private TableColumn delGuideTableContact;
	@FXML
	private Button delGuideClearSelection;
	@FXML
	private Button delGuideDelete;
	@FXML
	private Button delGuideModifySelected;

	// Event Listener on TextField[#regGuideEmail].onAction
	@FXML
	public void regGuideDoRegister(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on PasswordField[#regGuidePassword].onAction
	@FXML
	public void regGuideDoRegister(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#regPasswordShow].onAction
	@FXML
	public void regDoRegister(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#regGuideName].onAction
	@FXML
	public void regGuideDoRegister(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#regGuideContact].onAction
	@FXML
	public void regGuideDoRegister(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#regGuideClear].onAction
	@FXML
	public void regGuideDoClear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#regGuideRegister].onAction
	@FXML
	public void regGuideDoRegister(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#modGuideEmail].onAction
	@FXML
	public void modGuideDoModify(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on PasswordField[#modGuidePassword].onAction
	@FXML
	public void modGuideDoModify(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#modPasswordShow].onAction
	@FXML
	public void modDoModify(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#modGuideName].onAction
	@FXML
	public void modGuideDoModify(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#modGuideContact].onAction
	@FXML
	public void modGuideDoModify(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modGuideClear].onAction
	@FXML
	public void modGuideDoClear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modGuideAutofill].onAction
	@FXML
	public void modGuideDoAutofill(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modGuideModify].onAction
	@FXML
	public void modGuideDoModify(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delGuideClearSelection].onAction
	@FXML
	public void delGuideDoClearSelection(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delGuideDelete].onAction
	@FXML
	public void delGuideDoDelete(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delGuideModifySelected].onAction
	@FXML
	public void delGuideDoModifySelected(ActionEvent event) {
		// TODO Autogenerated
	}
}
