package ca.mcgill.ecse.climbsafe.javafx.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.layout.StackPane;

public class MainPageController {
  @FXML
  private Button topBarCloseButton;
  @FXML
  private Button setupNMCButton;
  @FXML
  private Button membersButton;
  @FXML
  private Button guidesButton;
  @FXML
  private Button equipmentsButton;
  @FXML
  private Button bundlesButton;
  @FXML
  private Button assignmentsButton;
  @FXML
  private Button menuPayButton;
  @FXML
  private Button tripsButton;
  @FXML
  private StackPane mainStackPane;

  // Event Listener on Button[#topBarCloseButton].onAction
  @FXML
  public void topBarCloseClicked(ActionEvent event) {
    Platform.exit();
  }

  // Event Listener on Button[#setupNMCButton].onAction
  @FXML
  public void setupNMCClicked(ActionEvent event) {
    // TODO Autogenerated
  }

  // Event Listener on Button[#membersButton].onAction
  @FXML
  public void membersClicked(ActionEvent event) {
    // TODO Autogenerated
  }

  // Event Listener on Button[#guidesButton].onAction
  @FXML
  public void guidesClicked(ActionEvent event) {
    // TODO Autogenerated
  }

  // Event Listener on Button[#equipmentsButton].onAction
  @FXML
  public void equipmentsClicked(ActionEvent event) {
    // TODO Autogenerated
  }

  // Event Listener on Button[#bundlesButton].onAction
  @FXML
  public void bundlesClicked(ActionEvent event) {
    // TODO Autogenerated
  }

  // Event Listener on Button[#assignmentsButton].onAction
  @FXML
  public void assignmentsClicked(ActionEvent event) {
    // TODO Autogenerated
  }

  // Event Listener on Button[#menuPayButton].onAction
  @FXML
  public void menuPayClicked(ActionEvent event) {
    // TODO Autogenerated
  }

  // Event Listener on Button[#tripsButton].onAction
  @FXML
  public void tripsClicked(ActionEvent event) {
    // TODO Autogenerated
  }
}
